- alias: Tasmota SO Push
  initial_state: false
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffs/backlog
      payload: setoption56 1 ; setoption57 1 ; setoption65 1
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/backlog
      payload: setoption56 1 ; setoption57 1 ; setoption65 1
  id: d5782c25fcff4d8eb92e8d8a25b791dd
- id: e08d101efbff45138ab1f683bc27003c
  alias: Landscape Lighting ON
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    below: 3.5
  action:
  - service: light.turn_on
    entity_id:
    - light.front_landscape_lighting
    - light.wled_segment_1
    - light.wled_main
    - light.front_of_the_house
- id: 1c1ef79f3ada4adaa8b632c0e6193eee
  alias: Landscape Lighting OFF
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
    above: -10
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.front_landscape_lighting
      - light.front_of_the_house
- id: '1601758186896'
  alias: Doorbell Rang
  description: When the Amcrest front doorbell button is pushed have an Alexa announcement
  trigger:
  - platform: mqtt
    topic: homeassistant/Doorbell/button
    payload: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.kitchen_echo_show
      - media_player.george_s_echo_show
      data:
        type: announce
      message: Someone is at the front door!
  - service: camera.snapshot
    entity_id: camera.doorbell
    data:
      entity_id: camera.doorbell
      filename: /media/snapshot_doorbell_{{ now().strftime("%Y-%m-%d.%H.%M") }}.jpg
  mode: single
- id: '1607539984638'
  alias: turn off wled at night
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - domain: light
    entity_id: light.wled_main
    device_id: 90ae17da521e46a48b6d378cc1810cca
    type: turn_off
  mode: single
- id: '1618450524880'
  alias: Dim Front Door Light
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_on
    device_id: cc24df0b7eaa42d893bdd05aa452a8a5
    entity_id: light.front_door
    domain: light
    brightness_pct: 20
  mode: single
- id: 239d893766404e2785e1cec63ff3d02e
  alias: Update OpenUV
  trigger:
  - platform: time_pattern
    minutes: /30
  condition:
  - condition: sun
    after: sunrise
    before: sunset
    before_offset: +00:45:00
  - condition: template
    value_template: "{{\n  state_attr('automation.update_openuv', 'last_triggered')
      == None\n  or (\n    now() - state_attr('automation.update_openuv', 'last_triggered')\n
      \ ) >= timedelta(hours = 0, minutes = 40)\n}}"
  action:
  - service: homeassistant.update_entity
    target:
      entity_id:
      - binary_sensor.protection_window
      - sensor.current_uv_index
    data: {}
- id: '1620744403963'
  alias: dim front door light
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_on
    device_id: cc24df0b7eaa42d893bdd05aa452a8a5
    entity_id: light.front_door
    domain: light
    brightness_pct: 20
  mode: single
- alias: Auto populate Hue group input select
  id: Auto populate Hue group input select
  mode: restart
  trigger:
    platform: event
    event_type: delayed_homeassistant_start
  action:
    service: input_select.set_options
    target:
      entity_id: input_select.hue_group
    data:
      options: "{{states.light\n  |selectattr('attributes.is_hue_group','eq',true)\n
        \ |map(attribute='name')|list }}\n"
- alias: Auto populate Hue dynamic scene input select
  id: Auto populate Hue dynamic scene input select
  mode: restart
  trigger:
  - platform: event
    event_type: delayed_homeassistant_start
  - platform: state
    entity_id: input_select.hue_group
  action:
    service: input_select.set_options
    target:
      entity_id: input_select.hue_dynamic_scene
    data:
      options: "{% set hue_group = states('input_select.hue_group') %} {{states.scene\n
        \ |selectattr('attributes.group_name','eq',hue_group)\n  |selectattr('attributes.is_dynamic','eq',true)\n
        \ |map(attribute='name')|list}}\n"
- id: '1718666528594'
  alias: Republish Channel 2 Data
  description: Republish Ambient Weather Data since the ID keeps changing
  trigger:
  - platform: mqtt
    topic: rtl_433/74930c0d-rtl433/devices/Ambientweather-F007TH/2/+/#
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: '{% set parts = trigger.topic.split(''/'') %}             rtl_433/74930c0d-rtl433/devices/Ambientweather-F007TH/FrontYard/{{
        parts[-1] }}'
      payload: '{{ trigger.payload }}'
  mode: parallel
  max: 8
- id: '1718668563238'
  alias: Republish Channel 1 Data
  description: Republish Ambient Weather Data since the ID keeps changing
  trigger:
  - platform: mqtt
    topic: rtl_433/74930c0d-rtl433/devices/Ambientweather-F007TH/1/+/#
  condition: []
  action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: '{% set parts = trigger.topic.split(''/'') %}             rtl_433/74930c0d-rtl433/devices/Ambientweather-F007TH/BackYard/{{
        parts[-1] }}'
      payload: '{{ trigger.payload }}'
  mode: parallel
  max: 8
