sensor:
  - name: "Garage Temperature"
    state_topic: "tele/Garage_AFS/SENSOR"
    value_template: "{{ value_json['BME280'].Temperature }}"
    unit_of_measurement: "F"

  - name: "Garage Humidity"
    state_topic: "tele/Garage_AFS/SENSOR"
    value_template: "{{ value_json['BME280'].Humidity }}"
    unit_of_measurement: "%"

  - name: "Garage Pressure"
    state_topic: "tele/Garage_AFS/SENSOR"
    value_template: "{{ value_json['BME280'].Pressure * 0.02953337 | round(2) }}"
    unit_of_measurement: "inHg"

switch:
  - name: "Garage Fan"
    state_topic: "stat/Garage_AFS/POWER4"
    command_topic: "cmnd/Garage_AFS/POWER4"
    availability_topic: "tele/Garage_AFS/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
    icon: mdi:fan

light:
  - name: "Kitchen Table Light"
    state_topic: "smartthings/Kitchen Table Light/switch/state"
    command_topic: "smartthings/Kitchen Table Light/switch"
    retain: true
    brightness_state_topic: "smartthings/Kitchen Table Light/level"
    brightness_command_topic: "smartthings/Kitchen Table Light/level"
    brightness_scale: 99
    brightness_value_template: "{{ value }}"
    qos: 0
    payload_on: "on"
    payload_off: "off"
    unique_id: 68f0af04-4d6a-481c-8c1f-21e04b9e1607

  # - name: "Front Room Light Switch" # Let Tasmota auto add it now
  #   state_topic: "stat/front-room_light_switch/POWER"
  #   command_topic: "cmnd/front-room_light_switch/POWER"
  #   availability_topic: "tele/front-room_light_switch/LWT"
  #   brightness_state_topic: "stat/front-room_light_switch/RESULT"
  #   brightness_command_topic: "cmnd/front-room_light_switch/Dimmer"
  #   brightness_scale: 100
  #   brightness_value_template: "{{ value_json.Dimmer }}"
  #   qos: 1
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   retain: false

  # - name: "2nd Set of Overhead Garage Lights" # Let Tasmota auto add it now
  #   state_topic: "stat/2ndGarageLights/RESULT"
  #   #value_template: "{{ value_json.POWER }}"
  #   command_topic: "cmnd/2ndGarageLights/POWER"
  #   availability_topic: "tele/2ndGarageLights/LWT"
  #   qos: 1
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   retain: false

  # - name: "Front Landscape Lighting" # Let Tasmota auto add it now
  #   state_topic: "stat/FrontLandscapeLights/RESULT"
  #   #value_template: "{{ value_json.POWER }}"
  #   command_topic: "cmnd/FrontLandscapeLights/POWER"
  #   availability_topic: "tele/FrontLandscapeLights/LWT"
  #   qos: 1
  #   payload_on: "ON"
  #   payload_off: "OFF"
  #   payload_available: "Online"
  #   payload_not_available: "Offline"
  #   retain: false

  - name: Garage Status Light
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    state_topic: "cmnd/Garage_AFS/power5"
    command_topic: "cmnd/Garage_AFS/power5"
    brightness_state_topic: "cmnd/Garage_AFS/Dimmer"
    brightness_command_topic: "cmnd/Garage_AFS/Dimmer"
    brightness_scale: 100
    rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
    rgb_state_topic: "cmnd/Garage_AFS/Color"
    rgb_command_topic: "cmnd/Garage_AFS/Color"
    effect_command_topic: "cmnd/Garage_AFS/Scheme"
    effect_state_topic: "cmnd/Garage_AFS/Scheme"
    state_value_template: "{{ value }}"
    brightness_value_template: "{{ value }}"
    effect_value_template: "{{ value }}"
    #rgb_command_mode: hex #191214 command not supported anymore
    retain: false
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
