substitutions:
  name: esp32-bluetooth-proxy-03230c
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: xiaomi_cgdk2
    mac_address: "58:2D:34:14:7E:15"
    bindkey: "4dc00e3825da22e79b804a246729c031"
    temperature:
      name: "CGDK2 Temperature"
    humidity:
      name: "CGDK2 Humidity"
    battery_level:
      name: "CGDK2 Battery Level"