esphome:
  name: ikeasensor1
  on_boot:
    priority: 600
    then:
    - wait_until:
        condition:
          api.connected:
        timeout: 8s


  platformio_options:
#    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
#    board_build.flash_size: 4MB

#    build_flags:
#      - -DARDUINO_USB_MODE=1
#      - -DARDUINO_USB_CDC_ON_BOOT=1

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  password: ""

# Enable logging
logger:
  level: VERBOSE
  hardware_uart: USB_SERIAL_JTAG


ota:
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# wifi:
#   ssid: !secret wifi_24ghz_ssid
#   password: !secret wifi_24ghz_password
#  output_power: "8.5"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Ikeasensor1 Fallback Hotspot"
  #   password: "CAuCnG74GJns"

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a
  frequency: 400kHz

uart:
  rx_pin: GPIO6
  tx_pin: GPIO7
  baud_rate: 9600
  id: pm_uart

sensor:
  - platform: sgp30
    eco2:
      name: "Air Quality 1 eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "Air Quality 1 TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 1s

  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter 2.5µm Concentration"
    uart_id: pm_uart
    update_interval: 20s

  - platform: adc
    pin: GPIO3
    name: "Ikea Sensor 1 Light"
    attenuation: auto
    accuracy_decimals: 3
    update_interval: 30s

  - platform: wifi_signal
    name: "Ikea Sensor 1 WiFi Strength"
    update_interval: 65s

output:
  - platform: ledc
    pin: GPIO0
    id: led_red
  - platform: ledc
    pin: GPIO1
    id: led_green
  - platform: ledc
    pin: GPIO8
    id: led_orange

  - platform: ledc
    pin: GPIO10
    frequency: 20000 Hz
    id: pm25_fan


light:
  - platform: monochromatic
    output: led_red
    name: "Ikea RED LED"
  - platform: monochromatic
    output: led_green
    name: "Ikea GREEN LED"
  - platform: monochromatic
    output: led_orange
    name: "Ikea ORANGE LED"

fan:
  - platform: speed
    name: "Ikea PM25 Fan"
    output: pm25_fan
    restore_mode: ALWAYS_OFF
