esphome:
  name: sht30-1

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "kJFK01ZaP5GpiVJHZp75RaI2tRExSa35Iw+pVprU3fc="

ota:
  password: "e56e532e7d6c8618e98e2acdc83122b3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sht30-1 Fallback Hotspot"
    password: "xiT7CFLsR3Rx"

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "Board 1 Temperature"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    humidity:
      name: "Board 1 Humidity"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    address: 0x45
    update_interval: 60s

# Example configuration entry
light:
  - platform: rgb
    name: "GardenSpot Strip"
    red: output_component1
    green: output_component2
    blue: output_component3

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D5
    max_power: 80%
  - platform: esp8266_pwm
    id: output_component2
    pin: D6
    max_power: 80%
  - platform: esp8266_pwm
    id: output_component3
    pin: D7
    max_power: 80%