esphome:
  name: sht30-1

esp8266:
  board: d1_mini_pro

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "kJFK01ZaP5GpiVJHZp75RaI2tRExSa35Iw+pVprU3fc="

ota:
  platform: esphome
  password: "e56e532e7d6c8618e98e2acdc83122b3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sht30-1 Fallback Hotspot"
    password: "xiT7CFLsR3Rx"

captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "Board 1 Temperature"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    humidity:
      name: "Board 1 Humidity"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 15
    address: 0x45
    update_interval: 60s


light:
  - platform: rgb
    name: "GardenSpot Strip"
    red: output_component1
    green: output_component2
    blue: output_component3

    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s

# Create a light using the hbridge
  - platform: hbridge
    id: mainlight
    name: "Fairy Lights"
    pin_a: in1
    pin_b: in2

    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s


output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D6 #was D7
    max_power: 80%
  - platform: esp8266_pwm
    id: output_component2
    pin: D5 #was D4
    max_power: 80%
  - platform: esp8266_pwm
    id: output_component3
    pin: D0 #was D3
    max_power: 80%

# Specify the two pins of the h-bridge as PWM pins
  - platform: esp8266_pwm
    id: in1
    pin: D7 #was D6
  - platform: esp8266_pwm
    id: in2
    pin: D8 #was D5
